#!/usr/bin/env bash

createScriptFolder () {
sudo apt-get -y install git
sleep .15
mkdir ~/.bitlincScript && cd ~/.bitlincScript
git clone https://github.com/bitlinc/btcinstaller.git
cd ~/.bitlincScript && cd btcinstaller
chmod a+x functions
chmod a+x updateScript
}

createAlias () {
USERNAME=$(whoami)    
echo "alias btcinstaller='/home/"$USERNAME"/.bitlincScript/btcinstaller/functions'" >> ~/.bashrc 
}

reloadBash () {
source ~/.bashrc
reset 
}

chmodFiles () {
cd $HOME
cd ~/.bitlincScript
cd btcinstaller
chmod a+x functions
chmod a+x updateScript
chmod a+x bitcoinCoreScript
}

createFirstApplication () {
cd $HOME && cd Desktop
sudo echo "[Desktop Entry]" >> Start.desktop
echo "Encoding=UTF-8" >> Start.desktop
echo "Name=Run BTC Installer" >> Start.desktop
echo "Exec=gnome-terminal --title "Updating to the newest version"  --tab -- /home/linux/.bitlincScript/btcinstaller/updateScript" >> Start.desktop
echo "Icon=utilities-terminal" >> Start.desktop
#echo "Terminal=false" >> Start.desktop
echo "Type=Application" >> Start.desktop
echo "Name[en_US]=Update" >> Start.desktop
chmod a+x Start.desktop
    }

createSecondApplication () {
cd $HOME && cd Desktop
sudo echo "[Desktop Entry]" >> Update.desktop
echo "Encoding=UTF-8" >> Update.desktop
echo "Name=Run BTC Installer" >> Update.desktop
echo "Exec=gnome-terminal --title "Bitcoin Installer: To Exit type control + C"  --window -- /home/linux/.bitlincScript/btcinstaller/functions" >> Update.desktop
echo "Icon=utilities-terminal" >> Update.desktop
#echo "Terminal=false" >> Start.desktop
echo "Type=Application" >> Update.desktop
echo "Name[en_US]=Bitcoin Installer" >> Update.desktop
chmod a+x Update.desktop
    }



createScriptFolder
createAlias
reloadBash
createFirstApplication
createSecondApplication
cd $Desktop
cd Desktop
rm -rf bitcoinCoreScript
#chmodFiles


#gnome-terminal --title Bitcoind_"$USERGIVENNETWORKCHOICE" --tab -e 'sh -c bitcoind'
#echo "Exec=sh -c cd $HOME; cd Desktop; git clone bitlinc/btcinstaller.git" >> Start.desktop
