#!/usr/bin/env bash


removeDirectory () {
    cd $HOME
    cd ~/.bitlincScript
    sudo rm -rf btcinstaller
    }
updateScriptWithGitHub () {
    cd $HOME
    cd ~/.bitlincScript
    git clone https://github.com/bitlinc/btcinstaller.git
    cd ~/.bitlincScript
    cd btcinstaller
    chmod a+x functions
    chmod a+x updateScript
    }
reloadBash () {
source ~/.bashrc 
reset
}
echo "Step 1"   
removeDirectory 
sleep 2 
echo "checking version with GitHub"
echo "step 2"
reloadBash
sleep 2
echo "reloading Bash"
echo "step 3"
sleep 2   
updateScriptWithGitHub
echo "updating script"
echo "step 5"
sleep 2
echo "Update complete, thank you for downloading the newest version"
