#!/usr/bin/env bash


updateScriptWithGitHub () {
    cd $HOME
    rm -rf ~/.bitlincScript
    mkdir ~/.bitlincScript && cd ~/.bitlincScript
    git clone https://github.com/bitlinc/btcinstaller.git
    cd ~/.bitlincScript && cd btcinstaller
    }
updateScriptWithGitHub
cd ~/.bitlincScript && cd btcinstaller
chmod a+x functions
chmod a+x bitcoinCoreScript
chmod a+x updateScript 





